// Seed content, carried over verbatim from the Job Hunt HQ artifact (scan of 18 Aug 2026).
// After the first seed the database is the source of truth — this file is only the starting point.

export const SCAN = {
  scanned_on: '2026-08-18',
  sources: 'Berlin Startup Jobs, Startup Jobs, LinkedIn past-week',
  jobs_added: 21,
  summary:
    "Berlin's 'product engineer' title is now producing more relevant postings than 'full stack engineer'. Several postings name AI-assisted development as a requirement rather than a nice-to-have.",
};

export const JOBS = [
  // ---- Added by the scan of 18 Aug 2026 ----
  {c:"Neural Frames",r:"Product Engineer (Growth) — AI Music Video Platform",u:"https://www.linkedin.com/jobs/search/?keywords=Neural%20Frames%20Product%20Engineer%20Growth&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",top:1,fresh:1,tags:["React","Next.js","TypeScript","Python","Easy Apply","Posted 1 day ago","On-site 4d/week"],n:"Bootstrapped and profitable at $5M ARR, hiring their first product engineer on React/Next.js/TypeScript with a Python backend, and the posting states outright that they want someone who uses AI tools as a genuine extension of how they work. Berlin Sessions is the credential here — you built and shipped a product for music creators solo, which is exactly the funnel-owning builder role they describe."},
  {c:"NXT Hero",r:"Senior Product Engineer (TypeScript) — Remote",u:"https://www.linkedin.com/jobs/search/?keywords=NXT%20Hero%20Senior%20Product%20Engineer%20TypeScript&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",remote:1,fresh:1,top:1,tags:["bis €85.000","TypeScript","Remote","Easy Apply","Actively reviewing"],n:"Published band up to €85k, fully remote, Easy Apply, and flagged as actively reviewing applicants — the lowest-friction application in this batch. TypeScript product engineering is your centre of gravity, so this is a straight stack match rather than a stretch."},
  {c:"Cohere",r:"Senior Full-Stack Engineer (Front-End Leaning) — EU Remote",u:"https://www.linkedin.com/jobs/search/?keywords=Cohere%20Senior%20Full-Stack%20Engineer%20Front-End%20Leaning&f_TPR=r604800",city:"Remote",type:"Full-time",top:1,fresh:1,tags:["Remote EU","Frontier AI lab","Front-end leaning"],n:"Frontier AI lab hiring a deliberately front-end-leaning full-stack engineer, remote anywhere in the EU. Your Deck.gl point-cloud viewer is the kind of hard browser-rendering work that separates a front-end-leaning candidate from a generic React one, and heavy agentic-AI workflow is table stakes rather than a novelty here."},
  {c:"Passionfroot",r:"Senior / Staff Product Engineer",u:"https://www.linkedin.com/jobs/search/?keywords=Passionfroot%20Senior%20Staff%20Product%20Engineer&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,top:1,tags:["Hybrid","Product engineer","Posted 2 days ago"],n:"Creator-economy booking platform, Berlin hybrid, posted two days ago. Product-engineer framing at a small team is where sole-ownership evidence like the Magnificode rescue outweighs a formal seniority ladder."},
  {c:"Clera",r:"Product Engineer",u:"https://www.linkedin.com/jobs/search/?keywords=Clera%20Product%20Engineer&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,tags:["Early applicant","On-site","Posted 1 day ago"],n:"Posted a day ago and still flagged 'be an early applicant', which is the window that measurably changes reply rates. Small Berlin team, so expect breadth rather than a narrow slice of the stack."},
  {c:"Almedia",r:"Founding Engineer",u:"https://www.linkedin.com/jobs/search/?keywords=Almedia%20Founding%20Engineer&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,top:1,tags:["Founding role","Equity","On-site"],n:"Founding-engineer roles care least about years-on-paper and most about proof you can take something from nothing to shipped alone. That is the single strongest line on your CV, so this category deserves more of your week than the scale-up postings do."},
  {c:"Limehome",r:"Product Engineer — Mid Level (d/f/m)",u:"https://www.linkedin.com/jobs/search/?keywords=Limehome%20Product%20Engineer%20Mid%20Level&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,tags:["Hybrid","Mid-level"],n:"Explicitly advertised at mid level, which most Berlin product-engineer postings are not. Tech-enabled hospitality — less mission-driven than your preference, but a realistic, non-senior-gated entry point."},
  {c:"Cint",r:"Senior Frontend / Fullstack Engineer",u:"https://startup.jobs/senior-frontend-fullstack-engineer-cint-8973425",city:"Berlin",type:"Full-time",fresh:1,tags:["Hybrid","Frontend-leaning"],n:"Market-research data platform, Berlin hybrid, posted 10 Aug. Frontend-leaning full-stack with a large data layer underneath, which is close in shape to the DagsHub work."},
  {c:"VREY",r:"Full-Stack Product Engineer (Ruby on Rails) — Solar Startup",u:"https://www.linkedin.com/jobs/search/?keywords=VREY%20Full-Stack%20Product%20Engineer%20Ruby%20on%20Rails&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",impact:1,fresh:1,tags:["Solar","Climate","Ruby on Rails","On-site"],n:"Genuine climate impact and VREY is currently the most active hirer on Berlin Startup Jobs, so the company is clearly scaling. The honest caveat is Ruby on Rails, which is nowhere in your stack — only worth the application if you are willing to argue transferability."},
  {c:"Wolters Kluwer",r:"Senior Full Stack Engineer — Libra Legal AI Assistant (m/f/d)",u:"https://www.linkedin.com/jobs/search/?keywords=Wolters%20Kluwer%20Senior%20Full%20Stack%20Engineer%20Libra&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,tags:["Hybrid","Legal AI","Enterprise"],n:"Large enterprise building an AI assistant product, Berlin hybrid. Structured process and English-speaking, but expect slower cycles than the startups above."},
  {c:"think-cell Software",r:"Senior Full Stack Developer",u:"https://www.linkedin.com/jobs/search/?keywords=think-cell%20Senior%20Full%20Stack%20Developer&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,tags:["On-site","Profitable","Berlin"],n:"Long-established, profitable Berlin software company known for paying well and for a demanding technical bar. On-site, so weigh that against your remote and hybrid preference."},
  {c:"Code Compass",r:"Fullstack Engineer (m/f/d) — Berlin / Vienna",u:"https://www.linkedin.com/jobs/search/?keywords=Code%20Compass%20Fullstack%20Engineer%20Berlin%20Vienna&f_TPR=r604800",city:"Berlin",type:"Full-time",remote:1,fresh:1,tags:["Remote","Berlin/Vienna"],n:"Remote across Berlin and Vienna. Smaller shop, so the process is usually short and founder-led rather than a multi-stage loop."},
  {c:"Xcede (recruiter)",r:"Engineering Manager — TypeScript, Node.js, React | Digital Trust",u:"https://www.linkedin.com/jobs/search/?keywords=Xcede%20Engineering%20Manager%20TypeScript%20Node%20React&location=Berlin%2C%20Germany",city:"Berlin",type:"Full-time",fresh:1,tags:["Up to €120k + bonus + stock","Hybrid","EM role","Review ~1 week"],n:"Up to €120k plus bonus and stock options is the highest published Berlin band in this batch, and the stack is exactly yours. It is a management title, so this is a stretch — but the recruiter relationship is worth opening regardless of whether you take this specific role."},
  {c:"Empathy",r:"Senior Full Stack Developer",u:"https://www.linkedin.com/jobs/search/?keywords=Empathy%20Senior%20Full%20Stack%20Developer&location=Tel%20Aviv%2C%20Israel",city:"Israel",type:"Full-time",impact:1,top:1,fresh:1,tags:["Bereavement support","Tel Aviv","On-site","Actively reviewing"],n:"Software that helps families through loss and the administrative aftermath of a death — one of the few genuinely mission-driven Israeli product companies hiring full-stack this week, and it is actively reviewing applicants. The teaching and community strand of your CV (MEET, we4water) reads as real signal to a company like this rather than as decoration."},
  {c:"Chamelio",r:"Fullstack Engineer",u:"https://www.linkedin.com/jobs/search/?keywords=Chamelio%20Fullstack%20Engineer&location=Tel%20Aviv%2C%20Israel",city:"Israel",type:"Full-time",top:1,fresh:1,tags:["Tel Aviv","On-site","1 connection works here","Posted 1 day ago"],n:"AI legal-intelligence startup, posted a day ago, and LinkedIn shows one of your connections already works there. A warm intro converts roughly ten times better than a cold application, so this is worth a message before it is worth an application."},
  {c:"Descope",r:"Senior Full Stack Engineer",u:"https://www.linkedin.com/jobs/search/?keywords=Descope%20Senior%20Full%20Stack%20Engineer&location=Tel%20Aviv%2C%20Israel",city:"Israel",type:"Full-time",fresh:1,tags:["Tel Aviv","Hybrid","Dev tools"],n:"Authentication developer tooling, hybrid Tel Aviv, posted a day ago. Developer-facing product work is close to what you did on the DagsHub GitHub integration."},
  {c:"Evergreen Finance",r:"Senior Full Stack Engineer",u:"https://startup.jobs/senior-full-stack-engineer-evergreen-finance-8983376",city:"Israel",type:"Full-time",fresh:1,tags:["Hybrid","Fintech"],n:"Posted 12 Aug, hybrid in Israel. Fintech rather than mission-driven, useful as pipeline volume for the Israeli side of your search."},
  {c:"Palo Alto Networks",r:"Senior Staff Fullstack Engineer — p-Cloud (Idira)",u:"https://startup.jobs/senior-staff-fullstack-engineer-p-cloud-idira-paloaltonetworks-com-8966350",city:"Israel",type:"Full-time",fresh:1,tags:["Security","Large org"],n:"Posted 9 Aug. Senior Staff is a real stretch at your level, but large organisations routinely down-level strong candidates rather than reject them, so the downside of applying is close to zero."},
  {c:"Toptal",r:"Freelance network — screening application",u:"https://www.toptal.com/developers/full-stack",city:"Remote",type:"Freelance",fresh:1,tags:["Channel","Screened network","Higher rates"],n:"Heavily screened network with a multi-stage entry process, but rates sit well above the open marketplaces and clients are pre-qualified. Your published NPM packages and the shipped LiDAR viewer are the kind of concrete artefacts their technical screen rewards."},
  {c:"Arc.dev",r:"Freelance marketplace — build a profile",u:"https://arc.dev/hire-developers/full-stack",city:"Remote",type:"Freelance",fresh:1,tags:["Channel","Remote-first"],n:"Remote-first freelance marketplace that indexes specifically for React, TypeScript, Next.js, Node and AWS — the exact stack string on your CV. Lower barrier than Toptal, so it is a cheap addition alongside Malt and freelancermap."},

  // ---- Earlier listings ----
  {c:"Ashby",r:"Senior Software Engineer, Product Engineering — EU",u:"https://www.linkedin.com/jobs/search/?keywords=Ashby%20Senior%20Software%20Engineer%20Product%20Engineering",city:"Remote",type:"Full-time",top:1,tags:["€108-145k","Remote EU","Product engineer"],n:"Fully remote across the EU, and the published band is roughly 35-80% above the Berlin median of about €80k. Ashby hires product engineers who own scope end to end, which is the exact shape of your Magnificode year. Highest-paying realistic target on this list."},
  {c:"Annapurna",r:"Senior Full Stack Developer (Python & TypeScript)",u:"https://www.linkedin.com/jobs/search/?keywords=Annapurna%20Senior%20Full%20Stack%20Developer%20Python%20TypeScript&location=Berlin",city:"Berlin",type:"Full-time",top:1,tags:["Python","TypeScript","Easy Apply","Hybrid"],n:"Exact stack match, marked 'actively reviewing applicants', and it is an Easy Apply. Lowest friction to highest relevance ratio in this batch — do this one first."},
  {c:"Stackgini",r:"Product Engineer (m/f/d) — €75-120k",u:"https://berlinstartupjobs.com/engineering/product-engineer-m-f-d-stackgini-gmbh/",city:"Berlin",type:"Full-time",top:1,tags:["€75-120k","Early applicant","Hybrid"],n:"Reposted within the last few hours and flagged 'be an early applicant', with the band published openly. Applying inside the first day or two measurably changes your odds here."},
  {c:"INSIDE M2M",r:"Fullstack Software Engineer — AI-Native Development",u:"https://www.linkedin.com/jobs/search/?keywords=INSIDE%20M2M%20Fullstack%20Software%20Engineer%20AI-Native&location=Berlin",city:"Berlin",type:"Full-time",top:1,tags:["AI-native","Hybrid"],n:"Second Berlin posting this month built explicitly around AI-native development. That framing is still rare and it rewards exactly the working style your GitHub already shows."},
  {c:"Octopus Energy",r:"Backend Engineer — Python / Heat pump ecosystem",u:"https://www.linkedin.com/jobs/search/?keywords=Octopus%20Energy%20Backend%20Engineer%20Python&location=Berlin",city:"Berlin",type:"Full-time",impact:1,tags:["€68-72k","Climate","German posting"],n:"Customer portal and heat-pump ecosystem at a major clean-energy company. Posting is in German so confirm the working language, and the band is below the Berlin median."},
  {c:"go-e",r:"Backend Software Engineer (m/f/x)",u:"https://www.linkedin.com/jobs/search/?keywords=go-e%20Backend%20Software%20Engineer&location=Berlin",city:"Berlin",type:"Full-time",impact:1,tags:["EV charging","Climate","Hybrid"],n:"EV charging hardware and software. Real climate impact with physical devices, closer to the sensor-data work you did for we4water than most web roles."},
  {c:"Personio",r:"Staff Software Engineer L6 (Full-stack / Backend) — Recruiting",u:"https://www.linkedin.com/jobs/search/?keywords=Personio%20Staff%20Software%20Engineer%20Recruiting&location=Berlin",city:"Berlin",type:"Full-time",remote:1,tags:["Remote","Scale-up"],n:"Remote from Berlin at one of Europe's biggest HR-tech companies. Staff level is a stretch, but large orgs down-level rather than reject."},
  {c:"LivePerson",r:"Senior Full Stack Software Engineer",u:"https://www.linkedin.com/jobs/search/?keywords=LivePerson%20Senior%20Full%20Stack%20Software%20Engineer&location=Berlin",city:"Berlin",type:"Full-time",remote:1,tags:["Remote","Conversational AI"],n:"Fully remote. LivePerson has a large Israeli engineering presence too, so this is one of the few employers where either base works."},
  {c:"Staffbase",r:"Staff Engineer — Fullstack",u:"https://www.linkedin.com/jobs/search/?keywords=Staffbase%20Staff%20Engineer%20Fullstack&location=Berlin",city:"Berlin",type:"Full-time",tags:["Hybrid","Scale-up"],n:"Employee communications platform, German unicorn. Staff title is a reach at your level."},
  {c:"Zentio / junini / sabia",r:"Founding Engineer (three separate Berlin startups)",u:"https://www.linkedin.com/jobs/search/?keywords=founding%20engineer&location=Berlin%2C%20Germany&f_TPR=r604800",city:"Berlin",type:"Full-time",top:1,tags:["Founding role","Equity"],n:"Three founding-engineer roles posted in Berlin in one week. This is the category that cares least about years-of-experience and most about proof you can ship a product alone, which is the single strongest thing on your CV."},
  {c:"Instaffo",r:"Product Engineer (all genders)",u:"https://www.linkedin.com/jobs/search/?keywords=Instaffo%20Product%20Engineer&location=Berlin",city:"Berlin",type:"Full-time",tags:["€65-90k","Hybrid"],n:"Band published. Product-engineer framing, mid-level friendly."},
  {c:"20°",r:"(Senior) Full-Stack Engineer — AI-Assisted 3D / CAD / BIM",u:"https://berlinstartupjobs.com/engineering/senior-full-stack-engineer-ai-assisted-3d-cad-bim-development-20-gmbh/",city:"Berlin",type:"Full-time",top:1,impact:1,tags:["React","Three.js","Supabase","Claude Code","Apply by email"],n:"Read this posting closely — it is the strongest match on the list by a distance. Browser 3D building editor for energy renovation: React 18 + TypeScript + Three.js/WebGL front end, NestJS + PostgreSQL + Supabase back end, geospatial coordinate transforms as a named bonus. They also state outright that they hire for fluency driving agentic tools like Claude Code, and that anyone who would rather hand-write everything is a bad fit. Your Deck.gl point-cloud viewer, Supabase work, and visible AI-assisted workflow cover almost every essential. Apply directly to hr@20grad.de with CV, start date and salary expectation; motivation letter optional but appreciated."},
  {c:"LiveEO",r:"Full-Stack Engineer (f/m/x)",u:"https://startup.jobs/full-stack-engineer-f-m-x-liveeo-gmbh-8016347",city:"Berlin",type:"Full-time",top:1,impact:1,tags:["Geospatial","Hybrid"],n:"Satellite-based infrastructure monitoring. Spatial data pipelines at scale, which is exactly the Lambda/LAZ pipeline story you already have."},
  {c:"Climatiq",r:"Senior Fullstack Engineer",u:"https://berlinstartupjobs.com/engineering/senior-fullstack-engineer-climatiq/",city:"Berlin",type:"Full-time",top:1,impact:1,tags:["Next.js","TypeScript"],n:"Carbon intelligence API. Explicitly pitches impact over balance sheet. Your we4water water-monitoring work is the natural opener."},
  {c:"AIDAR",r:"Senior Full-Stack Developer / Data Scientist",u:"https://berlinstartupjobs.com/engineering/senior-full-stack-developer-data-scientist-remote-friendly-aidar/",city:"Berlin",type:"Full-time",remote:1,top:1,tags:["Python","AI agents","Remote-friendly"],n:"AI artist scouting for A&Rs. Remote-friendly, EXIST-funded, paying customers. Berlin Sessions is a live credential here — you built a product for the same music scene they sell into."},
  {c:"ecosistant",r:"IT Operations & Automations (32h/week, remote possible)",u:"https://berlinstartupjobs.com/engineering/it-operations-automations-optimiere-mit-uns-recycling-in-europa-m-w-d-teilzeit-32h-woche-remote-moglich-ecosistant/",city:"Berlin",type:"Part-time",remote:1,impact:1,tags:["GreenTech","32h","German"],n:"Recycling compliance for e-commerce. One of very few genuinely advertised 32h roles. Posting is in German — worth checking their working language."},
  {c:"EMS Press",r:"Head of Technology (part-time, senior)",u:"https://berlinstartupjobs.com/engineering/head-of-technology-ems-press/",city:"Berlin",type:"Part-time",impact:1,tags:["React","TypeScript","Leadership"],n:"Academic publisher, part-time senior role reporting to the MD. Stretch on the leadership title, but the mix of hands-on judgement plus project delivery matches how you worked at Magnificode."},
  {c:"YGO",r:"Product Engineer (Backend, AI-First)",u:"https://berlinstartupjobs.com/engineering/product-engineer-backend-ai-first-hands-on-ygo/",city:"Berlin",type:"Full-time",remote:1,tags:["Go","Claude Code","Remote"],n:"Explicitly wants engineers who ship with Claude Code and other AI tools. You have Go from DagsHub and a visible AI-tooling habit. Rare posting where your side projects are the qualification."},
  {c:"autarc",r:"Mid & Senior Fullstack Engineers (Services)",u:"https://startup.jobs/mid-senior-fullstack-engineers-services-autarc-7998818",city:"Berlin",type:"Full-time",impact:1,tags:["Climate","Heat pumps"],n:"Heat pump planning software. Explicitly open to mid-level, which most Berlin senior postings are not."},
  {c:"Bees & Bears",r:"Senior Fullstack Engineer (m/f/d)",u:"https://startup.jobs/senior-fullstack-engineer-m-f-d-bees-bears-gmbh-8244475",city:"Berlin",type:"Full-time",impact:1,tags:["Climate fintech"],n:"Financing for home energy transition. Climate plus fintech."},
  {c:"voize",r:"Senior Fullstack Engineer (m/f/d)",u:"https://startup.jobs/senior-fullstack-engineer-m-f-d-voize-8125659",city:"Berlin",type:"Full-time",impact:1,tags:["Health","Voice AI","Hybrid"],n:"Voice AI for nursing documentation. Strong mission story, well funded."},
  {c:"Vara",r:"Data Engineer (fixed-term / internship)",u:"https://berlinstartupjobs.com/engineering/data-engineer-befristet-oder-als-praktikum-w-m-d-vara/",city:"Berlin",type:"Contract",impact:1,tags:["Health AI","Fixed-term"],n:"Breast cancer screening AI. Fixed-term parental cover — a contract-shaped way into a mission company."},
  {c:"Pandata",r:"Full Stack Developer",u:"https://berlinstartupjobs.com/engineering/full-stack-developer-pandata-gmbh/",city:"Berlin",type:"Full-time",tags:["Next.js","TypeScript","AI agents"],n:"Data consultancy in central Berlin. Consultancies are the usual doorway to freelance contracts too — worth asking even if you skip the FT role."},
  {c:"Small Improvements",r:"Senior Fullstack Developer with Product Mindset",u:"https://berlinstartupjobs.com/engineering/senior-fullstack-developer-with-product-mindset-small-improvements/",city:"Berlin",type:"Full-time",tags:["React","TypeScript","Remote-first hybrid"],n:"Remote-first but Berlin-based. Asks 6+ years, so this is a stretch on paper — the product-ownership framing is where you win it."},
  {c:"Taktile",r:"Senior Full-Stack Engineer — Platform team",u:"https://startup.jobs/senior-full-stack-engineer-platform-team-taktile-8582976",city:"Berlin",type:"Full-time",tags:["Platform","Hybrid"],n:"Decision automation for risk teams. Platform work maps well to your DagsHub integrations experience."},
  {c:"Zenjob",r:"Full-Stack Engineer (f/m/d)",u:"https://startup.jobs/full-stack-engineer-f-m-d-zenjob-com-8747016",city:"Berlin",type:"Full-time",tags:["Hybrid"],n:"Student side-job marketplace. Not senior-gated, decent mid-level entry point."},
  {c:"SumUp",r:"Full Stack Engineer — Billings & Subscriptions",u:"https://startup.jobs/full-stack-engineer-billings-subscriptions-sumup-8009356",city:"Berlin",type:"Full-time",tags:["Fintech","Scale-up"],n:"Several full-stack openings across SumUp teams. Big Berlin employer, English-speaking, structured process."},
  {c:"smava",r:"Senior Full Stack Engineer — Credit Card (Node, React, TS)",u:"https://startup.jobs/senior-full-stack-engineer-credit-card-f-m-d-nodejs-react-typescript-smava-gmbh-8797069",city:"Berlin",type:"Full-time",tags:["Node","React","TypeScript"],n:"Stack match is exact. Less mission-driven, useful as pipeline volume and interview practice."},
  {c:"Buena",r:"Senior Software Engineer (m/f/d)",u:"https://berlinstartupjobs.com/engineering/senior-software-engineer-m-f-d-buena/",city:"Berlin",type:"Full-time",tags:["PropTech","GV-backed"],n:"GV-backed, Germany's second-largest property manager. Fast-scaling."},
  {c:"Cito Transport Technologies",r:"Senior Full Stack Developer — remote",u:"https://startup.jobs/senior-full-stack-developer-m-w-d-remote-cito-transport-technologies-gm-7952726",city:"Berlin",type:"Full-time",remote:1,tags:["Remote","Logistics"],n:"Fully remote from Germany. Posting is in German."},
  {c:"Stackgini",r:"Product Engineer (m/f/d)",u:"https://berlinstartupjobs.com/engineering/product-engineer-m-f-d-stackgini-gmbh/",city:"Berlin",type:"Full-time",tags:["Product engineer"],n:"IT application-portfolio intelligence. 'Product engineer' framing suits someone who owns end-to-end delivery."},
  {c:"Tomorrow.io",r:"AI First — Senior Full Stack Engineer",u:"https://startup.jobs/ai-first-senior-full-stack-engineer-tomorrowio-8741044",city:"Israel",type:"Full-time",top:1,impact:1,tags:["Climate data","Tel Aviv"],n:"Weather and climate intelligence. Environmental data platform — the single closest Israeli match to your we4water monitoring work."},
  {c:"Eleos Health",r:"Senior Full Stack Developer",u:"https://startup.jobs/senior-full-stack-developer-eleos-health-company-8788162",city:"Israel",type:"Full-time",impact:1,tags:["Mental health","AI"],n:"AI for behavioural health care. Your MEET teaching background reads as a genuine signal here, not decoration."},
  {c:"accessiBe",r:"Full Stack Developer",u:"https://startup.jobs/full-stack-developer-accessibe-8820148",city:"Israel",type:"Full-time",impact:1,tags:["Accessibility"],n:"Web accessibility. Note the company has drawn public criticism over overlay-based accessibility — worth reading up before you decide."},
  {c:"WalkMe",r:"Full Stack Engineer — AI Applications",u:"https://startup.jobs/full-stack-engineer-ai-applications-walkme-8704651",city:"Israel",type:"Full-time",tags:["AI","Tel Aviv"],n:"Several full-stack openings (AI Applications and Big Data Platform, mid and senior). Now part of SAP."},
  {c:"Irregular",r:"Senior Full-Stack Engineer",u:"https://startup.jobs/senior-full-stack-engineer-irregular-8291729",city:"Israel",type:"Full-time",tags:["AI security","Tel Aviv"],n:"Frontier AI security research lab. Small, high-signal team."},
  {c:"Cymulate",r:"AI Full-Stack Engineer",u:"https://startup.jobs/ai-full-stack-engineer-cymulate-8709431",city:"Israel",type:"Full-time",tags:["Security","AI"],n:"Security validation platform building out AI features."},
  {c:"Miggo Security",r:"Senior Full Stack Engineer | Data-Driven Infrastructure",u:"https://startup.jobs/senior-full-stack-engineer-data-driven-infrastructure-miggo-security-8338692",city:"Israel",type:"Full-time",tags:["Security","Hybrid"],n:"Early-stage app-detection startup. Data-infrastructure flavour of full-stack."},
  {c:"Connecteam",r:"Senior Full Stack Engineer",u:"https://startup.jobs/senior-full-stack-engineer-connecteam-8274388",city:"Israel",type:"Full-time",tags:["SaaS"],n:"Deskless-workforce SaaS. Large, stable product org."},
  {c:"Kodem",r:"Senior Full-Stack Engineer",u:"https://startup.jobs/senior-full-stack-engineer-kodem-8264378",city:"Israel",type:"Full-time",tags:["Security","Hybrid"],n:"Runtime application security, early stage."},
  {c:"Forter",r:"Senior Full Stack Engineer II — CX Offering",u:"https://startup.jobs/senior-full-stack-engineer-ii-cx-offering-forter-7961647",city:"Israel",type:"Full-time",tags:["Fintech"],n:"Fraud prevention at scale."},
  {c:"HUMAN",r:"Senior Fullstack Engineer",u:"https://startup.jobs/senior-fullstack-engineer-human-company-8740956",city:"Israel",type:"Full-time",tags:["Security","Hybrid"],n:"Bot detection and fraud. Hybrid Tel Aviv."},
  {c:"Cato Networks",r:"Full Stack Developer",u:"https://startup.jobs/full-stack-developer-cato-networks-7968225",city:"Israel",type:"Full-time",tags:["Networking"],n:"SASE networking. Large engineering org, not senior-gated."},
  {c:"AppWork",r:"Senior Full Stack Engineer",u:"https://startup.jobs/senior-full-stack-engineer-join-the-appwork-team-8910532",city:"Israel",type:"Full-time",tags:["Hybrid"],n:"Hybrid Tel Aviv, posted early August."},
  {c:"Malt",r:"Freelance marketplace — build a profile",u:"https://en.malt.de/",city:"Remote",type:"Freelance",top:1,tags:["Channel","0% fee"],n:"Europe's dominant freelance marketplace, very strong in Germany. Freelancers pay 0% — the client covers the fee. Includes professional liability insurance in every contract, which removes a real objection for German clients."},
  {c:"freelancermap",r:"IT project marketplace — build a profile",u:"https://www.freelancermap.com/projects/deutschland",city:"Remote",type:"Freelance",top:1,tags:["Channel","0% commission"],n:"0% commission, thousands of German IT projects, heavy recruiter outreach. Specialists often get approached before projects are publicly listed, so a complete profile is the whole game."},
  {c:"Berlin Startup Jobs",r:"Freelance / contracting board",u:"https://berlinstartupjobs.com/contracting-positions/",city:"Berlin",type:"Freelance",tags:["Channel","Thin right now"],n:"Berlin-specific and free to check weekly, but currently down to a single live post and it is a sales role. Worth 30 seconds a week, not more."},
  {c:"Startup Jobs",r:"Part-time board",u:"https://startup.jobs/part-time-jobs",city:"Remote",type:"Part-time",tags:["Channel"],n:"Filtered feed of part-time startup roles, though this week it was almost entirely US retail and healthcare. They also run an MCP server at startup.jobs/mcp, which could feed this tracker automatically if you connect it."},
];

export const TARGETS = [
  {h:"Berlin — climate & impact",l:[
    ["Ecosia","Berlin's flagship mission company, currently hiring a CTO — which means the org is in motion and usually opens engineering roles around such a hire. Apply through their careers page, not the CTO posting."],
    ["Enpal / 1KOMMA5°","The two biggest German climate-tech scale-ups. High engineering headcount, continuous hiring, both cited as top Berlin climate employers."],
    ["Sunfire","Green hydrogen and industrial electrolysis. Heavier industrial data problems, close to the sensor/monitoring work you did for we4water."],
    ["Tomorrow / Ecolytiq / Doconomy","Sustainability-embedded fintech. Small teams, product-engineer shaped roles."],
    ["Berlin NGO and Stiftung tech teams","Betterplace, Wikimedia Deutschland, ProjectTogether. They contract out more than they hire, which suits a freelance pitch."],
  ]},
  {h:"Berlin — agencies & consultancies (best freelance entry)",l:[
    ["Pandata","Already hiring full-stack. Data consultancies bill projects out; ask about contract work in the same conversation."],
    ["Ackee, Neuland, Cusy, Ginetta, TheMonkeys","Berlin product studios that regularly subcontract React/TypeScript work. One email to each is a week's worth of pipeline."],
    ["Sanity / Vercel partner agencies","You have shipped a production Sanity + Grafana integration for a real client. That is a narrow, credible, well-paid niche and very few freelancers can claim it."],
  ]},
  {h:"Israel — mission-driven",l:[
    ["Tomorrow.io","Climate data, already hiring. Top of the list."],
    ["Empathy","Bereavement and loss support, hiring full-stack this week and actively reviewing."],
    ["Via","Public transit. The May posting has aged out of the tracker, but they hire continuously — check their careers page directly."],
    ["Eleos Health","Mental health AI. Hiring."],
    ["Sight Diagnostics, Aidoc, Nucleai","Health AI in Tel Aviv. Continuous full-stack hiring."],
    ["8200 Impact, PresenTense, Tech2Peace","Israeli impact accelerators. Portfolio companies hire, and your MEET history is directly relevant currency here."],
  ]},
  {h:"Warm network — ask these first",l:[
    ["Your Chamelio connection","LinkedIn shows one of your connections works at Chamelio, which is hiring a fullstack engineer in Tel Aviv this week. Message them before you apply."],
    ["DagsHub alumni","Three years there. Former colleagues have scattered into MLOps and AI startups across Israel and Europe. This is your highest-conversion channel and costs nothing."],
    ["Magnificode founders","You rescued a failed build for them. Ask directly for two referrals to other founders — people who have been rescued refer well."],
    ["MEET network","Alumni and staff across a decade, many now founders. Explicitly ask about part-time and contract work, not just jobs."],
    ["Mamram cohort","IDF elite program cohorts stay tight and are now senior enough to hire."],
    ["Berlin Sessions users","You built a tool the Berlin music-tech and community scene uses. That is a warm list of people who already know your work."],
  ]},
];

export const OUTREACH = [
  {t:"Cold — freelance pitch to an agency or studio",b:`Subject: Freelance full-stack capacity in Berlin (React / TypeScript / Python)

Hi [Name],

I'm a full-stack engineer in Berlin with capacity for freelance work from [month].

Most recently I was the sole engineer on a LiDAR point-cloud visualizer for a stealth startup — I took it from a failed first attempt to a shipped MVP, owning frontend, backend and infra. That meant a serverless AWS pipeline handling scans up to ~10M points and 1.2GB, Deck.gl 3D visualization, and published NPM packages for the viewer components.

Before that, three years full-time at DagsHub (MLOps platform) in Go, Python, React and Kubernetes.

If you ever need to hand off a project or add a pair of hands mid-sprint, I'd be glad to be on your list. Recent work and CV: idonov.com

Best,
Ido`},
  {t:"Cold — application to a mission-driven company",b:`Subject: Full-stack engineer — [Role], and why this one

Hi [Name],

I'm applying for [Role]. Quick reason it's not a generic application: I currently build the public platform for we4water, an NGO doing water projects, including a real-time water-quality monitoring view backed by a Grafana integration I wrote and a Sanity CMS the client edits themselves. Mission work is not a new interest I'm trying on.

On the engineering side: six years shipping production systems. Three at DagsHub building MLOps platform features in Go, Python, React and Kubernetes, then a year as sole engineer on a LiDAR visualizer, rebuilding the Python backend into a serverless AWS pipeline that processes scans up to ~10M points.

[One specific sentence about their product or problem.]

CV and projects: idonov.com

Best,
Ido`},
  {t:"Warm — referral ask to a former colleague",b:`Hi [Name],

Hope you're well — [one genuine line about them].

I'm opening up my search: full-stack roles in Berlin or Israel, and I'm flexible on shape — full-time, part-time or freelance contracts all work.

Since DagsHub I spent a year as sole engineer on a LiDAR point-cloud product, plus freelance work with Sanity, AWS and Grafana. The stack is still Go, Python, React and TypeScript.

Two things that would help:
1. If anything's open where you are, I'd love an intro.
2. If not, is there one person you'd point me to?

No rush, and happy to return the favour.

Ido`},
  {t:"Warm — connection at a company that is hiring right now",b:`Hi [Name],

Good to see you're at [Company] — [one genuine line about the company or their work].

I noticed you're hiring a [Role]. I'm looking at the moment: six years full-stack, three at DagsHub (Go, Python, React, Kubernetes), then a year as sole engineer taking a LiDAR point-cloud product from a failed first attempt to a shipped MVP.

Would you be open to a quick call about what the team actually needs? And if it's not the right fit, I'd rather hear that from you than from a rejection email.

Ido`},
  {t:"Follow-up — one week after applying, no reply",b:`Hi [Name],

Following up on my application for [Role] last week — still very interested.

Since writing I [shipped X / read Y about your product], which made me more sure this is the right fit. Happy to do a short call whenever suits.

Ido`},
];

export const PLAY = [
  {h:"Weekly rhythm",b:["Monday: open this tracker, filter to 'New this week', pick 5 to apply to.","Tuesday and Thursday: 3 warm outreach messages each. Warm beats cold roughly ten to one.","Wednesday: one freelance channel action — refresh a Malt or freelancermap profile, or pitch one agency.","Friday: follow up on anything sent 7+ days ago that went quiet. Most replies come from the follow-up, not the first message."]},
  {h:"Three CV variants worth keeping",b:["Freelance: lead with the Magnificode rescue and the client-facing Sanity/Grafana work. Day rate ready, no salary talk.","Full-time product engineer: lead with DagsHub scope and the Hacker News blog that drove 15k visitors in a day. That number is unusually strong and most engineers have nothing like it.","Part-time / fractional: lead with sole-engineer ownership and shipping speed. Frame the 20-30h as a feature — you deliver scoped outcomes, not seat time."]},
  {h:"Fix your CV first — it undersells you by about three years",b:["Your CV opens with '4+ years of experience'. Your LinkedIn lists Programmer at the IDF from Apr 2019 to Jun 2021, which the CV files under Education as Mamram and therefore does not count. That is 2 years 3 months of paid professional programming being thrown away.","Add it up: IDF Apr 2019 to Jun 2021, DagsHub Aug 2021 to Feb 2024, freelance Aug 2024 to now. That is roughly 6 years 9 months of engineering with one 6-month gap. Say '6+ years', not '4+'.","This single edit moves you from below the bar to above it on almost every 'Senior, 6+ years' posting in this tracker. Nothing else in this plan is a bigger return for less effort.","While you are in there: the CV says 'Freelance Full Stack Engineer / Magnificode' but LinkedIn says 'Various Startups'. Pick one story. Naming the client is stronger unless you are under NDA."]},
  {h:"LinkedIn audit — currently near-invisible",b:["'Open to Work' is switched off. Recruiters filter on it constantly and you are excluded from every one of those searches by default. You can restrict it to recruiters only so your current clients never see it. Turn it on.","Analytics for the past 7 days: 17 profile views, 4 search appearances, 2 post impressions. That is close to zero discoverability in a city where sourcing runs on LinkedIn.","Your Top Skills read Git, Python, JavaScript. Those are generic and none of them is your pitch. Reorder to React, TypeScript, Go, AWS, Next.js. Skills drive search matching, so this is not cosmetic.","243 connections and 253 followers is thin. Connect with the DagsHub alumni and Mamram cohort you already know. Reach compounds into recruiter visibility.","You have never posted. You wrote a blog that reached the Hacker News front page and pulled 15k readers in a day, and none of that exists on the platform where hiring happens. Three posts — the LiDAR rescue, the we4water Grafana integration, Berlin Sessions — would outrank most engineers in your network.","Mamram appears only as a certification line. A 6-month program with a 4% acceptance rate belongs in Education where German and Israeli recruiters will actually see it. Your Education section currently shows only 'harel, Computer Science, 2016-2018'.","No Projects or Featured section. Berlin Sessions, we4water and the LiDAR viewer are your best evidence and they are buried inside the About paragraph."]},
  {h:"What the market looked like this week",b:["Berlin's 'product engineer' title is now producing more relevant postings than 'full stack engineer' — Neural Frames, NXT Hero, Clera, Limehome and Passionfroot all landed in the past-week product-engineer search, while the full-stack search returned mostly recruiters and EMEA-remote agencies. Search both titles every week.","Several postings this week name AI-assisted development as a requirement rather than a nice-to-have (Neural Frames, YGO, INSIDE M2M, 20°). That is a category where your working style is the qualification, and it barely existed as a filter a year ago.","Published salary bands are still concentrated on LinkedIn: NXT Hero at up to €85k, Xcede at up to €120k plus bonus and stock. The startup boards almost never publish. Anchor negotiations on the LinkedIn numbers.","The Israeli listings are heavily security and fintech, with Empathy the main mission-driven exception this week."]},
  {h:"Honest read on positioning",b:["Your About section is genuinely good and already states you are open to freelance, part-time or full-time and based in Berlin/Tel Aviv. The problem is not the writing, it is that almost nobody is reaching the page.","Your varied background (film, teaching, community) reads as either scattered or unusually capable depending entirely on framing. Tie each one to delivery: the video work is how you documented DagsHub features, the teaching is how you communicate with non-engineers.","Berlin median full-time tech salary is around €80k, with senior technical roles above €80-100k. Ashby's published €108-145k band and Stackgini's €75-120k are useful anchors — do not accept a first number below the middle of those without asking.","Freelance day rates in Berlin sit well above the salaried equivalent. Price deliberately rather than by feel."]},
  {h:"Where the freelance work actually comes from",b:["Malt and freelancermap: both 0% fee for you in Germany. Recruiters approach specialists directly, so a complete, specific profile matters more than applying.","Toptal is worth the screening effort for the rate difference; Arc.dev is a lower-barrier addition that indexes on your exact stack string.","Agencies and studios beat marketplaces for rate and repeat work. Five emails to Berlin product studios is the highest-leverage hour in this whole plan.","Your own network: the Magnificode founders and DagsHub alumni are the shortest path to a signed contract, and neither costs you anything to ask."]},
];
